import { Route } from '@/components/ui/side-navigation';

export const defaultRoutes: Route[] = [
  {
    id: 98,
    name: "Campaign management",
    type: "title" as const,
  },
  {
    id: 100,
    name: "Create",
    type: "create" as const,
    icon: { lucide: "CreateIcon" },
    subitems: [
      { id: 101, name: "Media plan", type: "single" as const, url: "/create/media-experience", icon: { lucide: "WalletCards" } },
      { id: 102, name: "Sponsored product campaign", type: "single" as const, url: "/create/sponsored-products", icon: { lucide: "ListStart" } },
      { id: 103, name: "Display campaign", type: "single" as const, url: "/create/display", icon: { lucide: "MonitorSpeaker" } },
      { id: 104, name: "Offline in-store campaign", type: "single" as const, url: "/create/offline-instore", icon: { lucide: "Store" } },
      { id: 105, name: "Digital in-store campaign", type: "single" as const, url: "/create/digital-instore", icon: { lucide: "MonitorPlay" } },
      { id: 106, name: "Offsite campaign", type: "single" as const, url: "/create/offsite", icon: { lucide: "Globe" } },
    ],
  },
  {
    id: 99,
    name: "Media plans",
    type: "single" as const,
    icon: { lucide: "WalletCards" },
    url: "/campaigns",
  },
  {
    id: 0,
    name: "Campaigns",
    type: "parent" as const,
    icon: { lucide: "Table" },
    subitems: [
      {
        id: 20,
        name: "Sponsored products",
        type: "single" as const,
        url: "/campaigns/sponsored-products",
      },
      {
        id: 21,
        name: "Display",
        type: "single" as const,
        url: "/campaigns/display",
      },
      {
        id: 22,
        name: "Digital in-store",
        type: "single" as const,
        url: "/campaigns/digital-instore",
      },
      {
        id: 23,
        name: "Offline instore",
        type: "single" as const,
        url: "/campaigns/offline-instore",
      },
      {
        id: 26,
        name: "Display offsite",
        type: "single" as const,
        url: "/campaigns/offsite",
      },
    ],
  },
  {
    id: 1,
    name: "Creatives",
    type: "parent" as const,
    icon: { lucide: "ImagePlus" },
    subitems: [
      {
        id: 30,
        name: "Display",
        type: "single" as const,
        url: "/creatives/display",
      },
      {
        id: 31,
        name: "Digital in-store",
        type: "single" as const,
        url: "/creatives/digital-instore",
      },
      {
        id: 32,
        name: "Offline in-store",
        type: "single" as const,
        url: "/creatives/offline-instore",
      },
      {
        id: 33,
        name: "Offsite",
        type: "single" as const,
        url: "/creatives/offsite",
      },
    ],
  },
  {
    id: 2,
    name: "Calendar",
    type: "parent" as const,
    icon: { lucide: "CalendarDays" },
    subitems: [
      {
        id: 40,
        name: "Sponsored products",
        type: "single" as const,
        url: "/calendar/sponsored-products",
      },
      {
        id: 41,
        name: "Display",
        type: "single" as const,
        url: "/calendar/display",
      },
      {
        id: 42,
        name: "Digital in-store",
        type: "single" as const,
        url: "/calendar/digital-instore",
      },
      {
        id: 43,
        name: "Offline instore",
        type: "single" as const,
        url: "/calendar/offline-instore",
      },
    ],
  },
  {
    id: 3,
    name: "Insights",
    type: "parent" as const,
    icon: { lucide: "BarChart3" },
    subitems: [
      {
        id: 50,
        name: "Dashboard",
        type: "single" as const,
        url: "/insights",
      },
      {
        id: 51,
        name: "Custom reports",
        type: "single" as const,
        url: "/insights/report",
      },
    ],
  },
  {
    id: 5,
    name: "Campaign Agent",
    type: "parent" as const,
    icon: { lucide: "MessageSquare" },
    subitems: [
      {
        id: 70,
        name: "New chat",
        type: "single" as const,
        url: "/chat",
      },
      {
        id: 71,
        name: "Budget analysis",
        type: "single" as const,
        url: "/chat/spend-analysis",
      },
      {
        id: 72,
        name: "New campaign",
        type: "single" as const,
        url: "/chat/new-campaign",
      },
      {
        id: 73,
        name: "Keyword suggestions",
        type: "single" as const,
        url: "/chat/keyword-suggestions",
      },
    ],
  },
  {
    id: 6,
    name: "Ad CRM",
    type: "single" as const,
    icon: { lucide: "Handshake" },
    url: "/ad-crm",
  },
  {
    id: 8,
    name: "Configuration",
    type: "title" as const,
  },
  {
    id: 9,
    name: "Display config",
    type: "single" as const,
    icon: { lucide: "MonitorSpeaker" },
    url: "/configuration/display",
    disabled: true,
  },
  {
    id: 10,
    name: "Sponsored products config",
    type: "single" as const,
    icon: { lucide: "ListStart" },
    url: "/configuration/sponsored-products",
    disabled: true,
  },
  {
    id: 11,
    name: "Digital in-store config",
    type: "single" as const,
    icon: { lucide: "MonitorPlay" },
    url: "/configuration/digital-instore",
    disabled: true,
  },
  {
    id: 12,
    name: "Offline in-store config",
    type: "single" as const,
    icon: { lucide: "Store" },
    url: "/configuration/offline-instore",
    disabled: true,
  },
  {
    id: 13,
    name: "Organisations & users",
    type: "single" as const,
    icon: { lucide: "OrganisationsIcon" },
    url: "/configuration/organisations-users",
  },
  {
    id: 14,
    name: "Brands & retail products",
    type: "single" as const,
    icon: { lucide: "BrandsIcon" },
    url: "/configuration/brands-products",
  },
  {
    id: 15,
    name: "Media Orchestra",
    type: "single" as const,
    icon: { lucide: "Settings2" },
    url: "/configuration/media-orchestra",
  },
];

// Extended routes for breadcrumb navigation (detail pages)
export const extendedRoutes: Route[] = [
  ...defaultRoutes,
  // Campaign detail routes
  {
    id: 200,
    name: "Campaign Details",
    type: "hidden" as const,
    url: "/campaigns/sponsored-products/[id]",
    pattern: "/campaigns/sponsored-products/*",
  },
  {
    id: 201,
    name: "Campaign Details",
    type: "hidden" as const,
    url: "/campaigns/display/[id]",
    pattern: "/campaigns/display/*",
  },
  {
    id: 202,
    name: "Campaign Details",
    type: "hidden" as const,
    url: "/campaigns/digital-instore/[id]",
    pattern: "/campaigns/digital-instore/*",
  },
  {
    id: 203,
    name: "Campaign Details",
    type: "hidden" as const,
    url: "/campaigns/offline-instore/[id]",
    pattern: "/campaigns/offline-instore/*",
  },
  {
    id: 206,
    name: "Campaign Details",
    type: "hidden" as const,
    url: "/campaigns/offsite/[id]",
    pattern: "/campaigns/offsite/*",
  },
  // Booking detail routes
  {
    id: 210,
    name: "Booking Details",
    type: "hidden" as const,
    url: "/campaigns/sponsored-products/booking/[bookingId]",
    pattern: "/campaigns/sponsored-products/booking/*",
  },
  {
    id: 211,
    name: "Booking Details",
    type: "hidden" as const,
    url: "/campaigns/display/booking/[bookingId]",
    pattern: "/campaigns/display/booking/*",
  },
  {
    id: 212,
    name: "Booking Details",
    type: "hidden" as const,
    url: "/campaigns/digital-instore/booking/[bookingId]",
    pattern: "/campaigns/digital-instore/booking/*",
  },
  {
    id: 213,
    name: "Booking Details",
    type: "hidden" as const,
    url: "/campaigns/offline-instore/booking/[bookingId]",
    pattern: "/campaigns/offline-instore/booking/*",
  },
  {
    id: 216,
    name: "Booking Details",
    type: "hidden" as const,
    url: "/campaigns/offsite/booking/[bookingId]",
    pattern: "/campaigns/offsite/booking/*",
  },
  // Creative detail routes
  {
    id: 220,
    name: "Creative Details",
    type: "hidden" as const,
    url: "/campaigns/sponsored-products/creative/[creativeId]",
    pattern: "/campaigns/sponsored-products/creative/*",
  },
  {
    id: 221,
    name: "Creative Details",
    type: "hidden" as const,
    url: "/campaigns/display/creative/[creativeId]",
    pattern: "/campaigns/display/creative/*",
  },
  {
    id: 222,
    name: "Creative Details",
    type: "hidden" as const,
    url: "/campaigns/digital-instore/creative/[creativeId]",
    pattern: "/campaigns/digital-instore/creative/*",
  },
  {
    id: 223,
    name: "Creative Details",
    type: "hidden" as const,
    url: "/campaigns/offline-instore/creative/[creativeId]",
    pattern: "/campaigns/offline-instore/creative/*",
  },
  {
    id: 226,
    name: "Creative Details",
    type: "hidden" as const,
    url: "/campaigns/offsite/creative/[creativeId]",
    pattern: "/campaigns/offsite/creative/*",
  },
  // Organisation routes
  { id: 300, name: "Organisation Details", type: "hidden" as const, url: "/configuration/organisations-users/[id]", pattern: "/configuration/organisations-users/[id]" },
  { id: 301, name: "User Details", type: "hidden" as const, url: "/configuration/organisations-users/users/[id]", pattern: "/configuration/organisations-users/users/*" },
  { id: 302, name: "Contract Details", type: "hidden" as const, url: "/configuration/organisations-users/contracts/[id]", pattern: "/configuration/organisations-users/contracts/*" },
  { id: 303, name: "Role Details", type: "hidden" as const, url: "/configuration/organisations-users/roles/[id]", pattern: "/configuration/organisations-users/roles/*" },
  // Brand routes
  { id: 310, name: "Brand Details", type: "hidden" as const, url: "/configuration/brands-products/[id]", pattern: "/configuration/brands-products/*" },
  { id: 311, name: "Product Details", type: "hidden" as const, url: "/configuration/brands-products/products/[id]", pattern: "/configuration/brands-products/products/*" },
];