import {
  BarChart2 as Performance,
  CalendarDays as BookingCalendar,
  ImagePlus as Creatives,
  MonitorPlay as Display,
  Settings2 as Yield,
  Table as Campaigns,
  Home,
  User,
  Settings,
  Settings2,
  FileText,
  Users,
  ShoppingCart,
  BarChart3,
  PieChart,
  TrendingUp,
  Activity,
  Table,
  ImagePlus,
  CalendarDays,
  ChartNoAxesColumn,
  LayoutDashboard,
  MessageSquare,
  MessageCircle,
  MessageCirclePlus,
  MonitorSpeaker,
  ListStart,
  MonitorPlay,
  Store,
  WalletCards,
  Globe,
  Handshake,
  Rows3,
  LayoutList,
  CirclePlus,
} from 'lucide-react';
import { OrganisationsIcon, BrandsIcon } from './custom-icons';

export const renderIcon = (icon: string) => {
  // Create uses the standard outline circle-plus so it matches the other
  // menu icons (no fill; inherits the nav icon stroke colour).
  if (icon === 'CreateIcon') {
    return <CirclePlus size={20} />;
  }

  const icons = {
    Display,
    Campaigns,
    Creatives,
    BookingCalendar,
    Performance,
    Yield,
    Home,
    User,
    Settings,
    Settings2,
    FileText,
    Users,
    ShoppingCart,
    BarChart3,
    PieChart,
    TrendingUp,
    Activity,
    Table,
    ImagePlus,
    CalendarDays,
    ChartNoAxesColumn,
    LayoutDashboard,
    MessageSquare,
    MessageCircle,
    MessageCirclePlus,
    MonitorSpeaker,
    ListStart,
    MonitorPlay,
    Store,
    WalletCards,
    Globe,
    Handshake,
    Rows3,
    LayoutList,
    OrganisationsIcon,
    BrandsIcon,
  };
  const IconComponent = icons[icon as keyof typeof icons];
  return IconComponent ? <IconComponent size={20} /> : null;
}; 